### ISSUE TITLE
test-fft.C fails to compile in 1.7.0

### ISSUE THREAD

**Issue by saraedum** [linbox-team/linbox#312]
Trying to build linbox for conda-forge, I get:

```
2024-04-20T15:26:25.7650582Z test-fft.C:177:32:   required from 'bool Checker<Field>::check(long unsigned int) [with Field = Givaro::Modular<long unsigned int, __int128 unsigned>]'
2024-04-20T15:26:25.7651755Z test-fft.C:221:25:   required from 'bool test_one_modular_implem(uint64_t, size_t, long unsigned int) [with ModImplem = Givaro::Modular; Elt = long unsigned int; C = {__int128 unsigned}; uint64_t = long unsigned int; size_t = long unsigned int]'
2024-04-20T15:26:25.7652430Z test-fft.C:278:65:   required from here
2024-04-20T15:26:25.7653130Z ../linbox/algorithms/polynomial-matrix/fft-integral.inl:386:28: error: 'const class Givaro::Modular<long unsigned int, __int128 unsigned>' has no member named 'mul_precomp_b_without_reduction'
2024-04-20T15:26:25.7654355Z   386 |                 this->fld->mul_precomp_b_without_reduction (B, B, alpha, alphap);
```

Full log is [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=919282&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3)

**Comment by saraedum** [comment]
I don't really understand what's going on, so I'll just disable that test for the time being.
